### ISSUE TITLE
Matching lines with quantity after ingredient

### ISSUE THREAD

**Issue by tmayoff** [jakeboone02/parse-ingredient#13]
I have lists of ingredients with their quantity measurement after the name of the ingredient. Currently the library doesn't recognize them, how difficult would it be to support that?

**Comment by jakeboone02** [comment]
Can you provide an example?

**Comment by jakeboone02** [comment]
Thanks, that helps. I'm on vacation right now but I can take a stab at this when I get back.

**Comment by jakeboone02** [comment]
@tmayoff I just published `v1.1.0-beta.0` which includes support for quantity/UOM at the end of each line (see #14 for the changes). Would you mind testing it with

```
npm i parse-ingredient@1.1.0-beta.0
```

and letting me know if it meets your requirement? I'll publish it as `v1.1.0` proper if it works for you.

**Comment by tmayoff** [comment]
Thanks very much for the work, will test this weekend!
