### ISSUE TITLE
Capitalized Tbps not being recognized

### ISSUE THREAD

**Issue by tmayoff** [jakeboone02/parse-ingredient#19]
The original issue in my repo: https://github.com/tmayoff/obsidian-meals/issues/66. 

It seems to just be an issue with the [alternates](https://github.com/StefanVDWeide/parse-ingredient/blob/76726ec936368160f7ade0ab50444486d535bdb5/src/index.ts#L95) only including `Tbsp.` and not `Tbsp`, I'll submit a pr for this

**Comment by WhyMe4** [comment]
Many of the alternative names currently require having a trailing period. I would suggest have all both with and without the period as alternates.

**Comment by jakeboone02** [comment]
This is resolved in [v1.2.1](https://github.com/jakeboone02/parse-ingredient/releases/tag/v1.2.1).
